# Generated by Django 4.2.4 on 2023-11-06 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorder',
            name='user',
        ),
        migrations.AddField(
            model_name='movieorder',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieorder',
            name='purchased_by',
            field=models.EmailField(max_length=254),
        ),
    ]
